CREATE TABLE "EMPLOYEE" (
"EMPLOYEE_ID" NUMBER(5,0) NOT NULL,
"PASSWORD" VARCHAR2(12) NOT NULL,
"EMPLOYEE_NAME" VARCHAR2(20) NOT NULL,
PRIMARY KEY ("EMPLOYEE_ID") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "EMPLOYEE"."EMPLOYEE_ID" IS '사원번호';
COMMENT ON COLUMN "EMPLOYEE"."PASSWORD" IS '사원비밀번호';
COMMENT ON COLUMN "EMPLOYEE"."EMPLOYEE_NAME" IS '사원번호';

CREATE TABLE "ITEM_MASTER" (
"ITEM_CODE" VARCHAR2(10) NOT NULL,
"ITEM_NAME" VARCHAR2(100) NOT NULL,
PRIMARY KEY ("ITEM_CODE") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "ITEM_MASTER"."ITEM_CODE" IS '품목코드';
COMMENT ON COLUMN "ITEM_MASTER"."ITEM_NAME" IS '픔목이름';

CREATE TABLE "ITEM_PRICE" (
"ITEM_CODE" VARCHAR2(10) NOT NULL,
"APPLY_DATE" VARCHAR2(8) NOT NULL,
"PRICE" NUMBER(5,0) DEFAULT 0 NULL,
PRIMARY KEY ("ITEM_CODE", "APPLY_DATE") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "ITEM_PRICE"."ITEM_CODE" IS '품목코드';
COMMENT ON COLUMN "ITEM_PRICE"."APPLY_DATE" IS '가격적용일자';

CREATE TABLE "ITEM_BALANCE" (
"ITEM_CODE" VARCHAR2(10) NOT NULL,
"WH_CODE" CHAR(2 ) NOT NULL,
"BEF_BALANCE" NUMBER(5,0) DEFAULT 0 NULL,
"RECEIPT_QTY" NUMBER(5,0) DEFAULT 0 NULL,
"ISSUE_QTY" NUMBER(5,0) DEFAULT 0 NULL,
PRIMARY KEY ("ITEM_CODE", "WH_CODE") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "ITEM_BALANCE"."ITEM_CODE" IS '품목번호';
COMMENT ON COLUMN "ITEM_BALANCE"."BEF_BALANCE" IS '전월재고';
COMMENT ON COLUMN "ITEM_BALANCE"."RECEIPT_QTY" IS '입고수량';
COMMENT ON COLUMN "ITEM_BALANCE"."ISSUE_QTY" IS '출고수량';

CREATE TABLE "WHAREHOUSE" (
"WH_CODE" CHAR(2 ) NOT NULL,
"WH_NAME" VARCHAR2(50) NOT NULL,
"LOC_CODE" VARCHAR2(4) NULL,
PRIMARY KEY ("WH_CODE") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "WHAREHOUSE"."WH_CODE" IS '창고코드';
COMMENT ON COLUMN "WHAREHOUSE"."WH_NAME" IS '창고이름';
COMMENT ON COLUMN "WHAREHOUSE"."LOC_CODE" IS '창고위치';

CREATE TABLE "LOCATION" (
"LOC_CODE" VARCHAR2(4) NOT NULL,
"LOCATION" VARCHAR2(100) NULL,
PRIMARY KEY ("LOC_CODE") 
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "LOCATION"."LOC_CODE" IS '위치코드';
COMMENT ON COLUMN "LOCATION"."LOCATION" IS '위치이름';

CREATE TABLE "ITEM_TRANSACTION" (
"ITEM_CODE" VARCHAR2(10) NULL,
"WH_CODE" CHAR(2 ) NULL,
"TR_TYPE" CHAR(1 ) NULL,
"TR_DATE" DATE DEFAULT SYSDATE NULL,
"TR_QTY" NUMBER DEFAULT 0 NULL
)
NOCOMPRESS 
NOPARALLEL ;

CREATE INDEX "IDX_ITEM_BALANCE" ON "ITEM_TRANSACTION" ("TR_DATE" DESC, "TR_TYPE" ASC, "ITEM_CODE" ASC, "WH_CODE" ASC);
COMMENT ON COLUMN "ITEM_TRANSACTION"."TR_TYPE" IS '입출고구분(R=입고, i=출고)';
COMMENT ON COLUMN "ITEM_TRANSACTION"."TR_DATE" IS '입출고일자';
COMMENT ON COLUMN "ITEM_TRANSACTION"."TR_QTY" IS '입출고수량';

CREATE TABLE "TR_CODE" (
"TR_TYPE" CHAR(2 ) NULL,
"TR_DESC" VARCHAR2(100) NULL
)
NOCOMPRESS 
NOPARALLEL ;

COMMENT ON COLUMN "TR_CODE"."TR_TYPE" IS '입출고유형';
COMMENT ON COLUMN "TR_CODE"."TR_DESC" IS '입출고설명';


ALTER TABLE "ITEM_PRICE" ADD CONSTRAINT "FK_ITEM_PRICE_ITEM_MASTER_1" FOREIGN KEY ("ITEM_CODE") REFERENCES "ITEM_MASTER" ("ITEM_CODE");
ALTER TABLE "ITEM_BALANCE" ADD CONSTRAINT "FK_ITEM_BALANCE_ITEM_MASTER_1" FOREIGN KEY ("ITEM_CODE") REFERENCES "ITEM_MASTER" ("ITEM_CODE");
ALTER TABLE "ITEM_BALANCE" ADD CONSTRAINT "FK_ITEM_BALANCE_WHAREHOUSE_1" FOREIGN KEY ("WH_CODE") REFERENCES "WHAREHOUSE" ("WH_CODE");
ALTER TABLE "WHAREHOUSE" ADD CONSTRAINT "FK_WHAREHOUSE_LOCATION_1" FOREIGN KEY ("LOC_CODE") REFERENCES "LOCATION" ("LOC_CODE");
ALTER TABLE "ITEM_TRANSACTION" ADD FOREIGN KEY ("ITEM_CODE", "WH_CODE") REFERENCES "ITEM_BALANCE" ("ITEM_CODE", "WH_CODE");

